{% set name = "httpauth" %}
{% set version = "0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/httpauth-{{ version }}.tar.gz
  sha256: 95e84f12ec58578490b1d2f545606a4cd1481b3da94a84ecfa79644397cf5fc3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=2.7
    - pip
  run:
    - python >=2.7

test:
  imports:
    - httpauth
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jonashaag/httpauth
  summary: WSGI HTTP Digest Authentication middleware
  license: ISC
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jonashaag
