{% set name = "httpauth" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/httpauth-{{ version }}.tar.gz
  sha256: 0baae716ba00779bce50b04cc2c2d2c9e48ae733d73848061c3498b7e3e6d9d4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - httpauth
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jonashaag/httpauth
  summary: WSGI HTTP Digest Authentication middleware
  license: ISC
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jonashaag
